FROM python:3.10-slim-buster

WORKDIR /app

COPY . .

RUN apt update && apt install -y awscli

RUN pip install --upgrade pip setuptools wheel && \
    pip install -e .
=
EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
