name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '*.md'

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/net-sec:latest

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Starting deployment to Render..."
        
          # Make the deployment request with proper error handling
          response=$(curl -s -w "%{http_code}" -X POST \
            "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{}')
        
          # Extract HTTP status code (last 3 characters)
          http_code="${response: -3}"
          response_body="${response%???}"
        
          echo "HTTP Status Code: $http_code"
          echo "Response Body: $response_body"
        
          # Check if deployment was successful
          if [ "$http_code" -eq 201 ] || [ "$http_code" -eq 200 ]; then
            echo "✅ Deployment triggered successfully!"
            
            # Extract deploy ID from response for tracking
            deploy_id=$(echo "$response_body" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
            if [ -n "$deploy_id" ]; then
              echo "Deploy ID: $deploy_id"
              echo "You can track the deployment at: https://dashboard.render.com/service/${RENDER_SERVICE_ID}"
            fi
          else
            echo "❌ Deployment failed with HTTP status code: $http_code"
            echo "Response: $response_body"
            exit 1
          fi